name: Release

on:
  push:
    tags:
      - "*"

jobs:
  meta:
    name: Meta-package
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ secrets.META_PACKAGE }}
          token: ${{ steps.generate-token.outputs.token }}
